apiVersion: api.unleash.crossplane.io/v1alpha1
kind: Token
metadata:
  annotations:
    meta.upbound.io/example-id: api/v1alpha1/token
  labels:
    testing.upbound.io/example-name: client_token
  name: unleash-client-token
  namespace: default
spec:
  forProvider:
    environment: development
    expiresAt: "2024-12-31T23:59:59Z"
    project: default
    tokenName: client-token-name
    type: client
