apiVersion: api.unleash.crossplane.io/v1alpha1
kind: Token
metadata:
  annotations:
    meta.upbound.io/example-id: api/v1alpha1/token
  labels:
    testing.upbound.io/example-name: client_token
  name: unleash-client-token
  namespace: default
spec:
  forProvider:
    environment: "*"
    expiresAt: "2024-10-19"
    projects:
      - "*"
    type: admin
    username: bobjoe
